site_name: Cours Bases de donn&eacute;es 2
site_url: https://bd2.kerzo.ca/
repo_url: https://github.com/jaixan/db2

nav:
  - 'Accueil': index.md
  - 'Modélisation':
      - 'Définition': modelisation/definition_modelisation.md
      - 'Modèle Entité-Association': modelisation/modele_entites_relations.md
      - 'Schéma conceptuel': modelisation/schema_conceptuel.md
      - 'Types de relations': modelisation/types_relations.md
      - 'Normalisation': modelisation/normalisation.md
      - 'Diagramme de classes UML': modelisation/classes.md

  - 'MySQL':
      - 'Création de base de données': mysql/creation_bd.md
      - 'Création de tables': mysql/creation_table.md
      - 'Convention de nommage': mysql/convention.md
      - 'Types de jointures': mysql/types_jointures.md
      - 'Vues': mysql/vues.md
      - 'Insertions': mysql/insertion.md
      - 'Déclencheurs': mysql/declencheurs.md
      - 'Fonctions': mysql/fonctions.md
      - 'Procédures stockées': mysql/procedures.md
      - 'Transactions': mysql/transactions.md
      - 'Gestion des erreurs': mysql/gestion_erreurs.md
      - 'Curseurs': mysql/curseurs.md
      - 'Sécurité':
          - 'Utilisateurs': mysql/utilisateurs.md
          - 'Autorisations': mysql/autorisations.md
          - 'Rôles': mysql/roles.md
  - 'Python':
      - 'Installation': python/installation.md
      - 'Environnement virtuel': python/venv.md
      - 'PIP': python/pip.md
      - 'Connexion à MySQL': python/mysql_connector.md
      - 'Flask': python/flask.md

  - 'Exercices':
      - Exercice 01 - Revision MySQL: exercices/ex01_enonce.md
      - Exercice 02 - Système de prise de présence en cours: exercices/ex02_enonce.md
      - Exercice 03 - Système de stationnement du cégep: exercices/ex03_enonce.md
      - Exercice 04 - Modélisation d'un livre de recettes: exercices/ex04_enonce.md
      - Exercice 05 - Exercice sur les insertions: exercices/ex05_enonce.md
      - Exercice 06 - Exercice sur les vues: exercices/ex06_enonce.md
      - Exercice 07 - Exercice sur les déclencheurs: exercices/ex07_enonce.md
      - Exercice 08 - Exercice sur les fonctions: exercices/ex08_enonce.md
      - Exercice 09 - Crédit social: exercices/ex09_enonce.md
      - Exercice 10 - Exercice sur les curseurs: exercices/ex10_enonce.md
      - Exercice 11 - Gestion des utilisateurs: exercices/ex11_enonce.md
      - Exercice 12 - pyCRUD: exercices/ex12_enonce.md
      - Exercice 13 - Flask: exercices/ex13_enonce.md

  - Évaluations:
      - Résumé des évaluations: evaluations/resume.md
      - Évaluation formative formelle: evaluations/evaluation_formative_formelle.md
      - Projet long: evaluations/projet_long.md
      - Révision:
          - Examen 01 - Révision A: evaluations/examen01_revision_a.md
          - Analyse - Révision: evaluations/analyse_revision_a.md
          - Évaluation finale - révision: evaluations/revision.md
  - 'Outils de travail':
      - DBeaver: outils/dbeaver.md
      - draw.io: outils/drawio.md
  - 'Horaire': horaire.md
  - 'À propos': apropos.md
theme:
  name: material
  icon:
    logo: fontawesome/solid/database
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.copy
    - toc.integrate
  language: fr
  palette:
    - scheme: light
      toggle: false
      primary: indigo
      accent: deep orange
plugins:
  - search: {}

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/alltarget.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
